### ISSUE TITLE
A few things

### ISSUE THREAD

**Issue by b-t-k** [dajare/elizabeth-gaskell_north-and-south#1]
So close to reviewing my first "perfect" book :-)

**Content.opf**
- _North of England_ in short desc but _north of England_ in long desc, A quick google seems to indicate the capped version is correct.
- “Although comparatively little read among Gaskell’s works in the earlier part…” is a bit awkward.
- wikipedia link is wrong: s/b https://en.wikipedia.org/wiki/North_and_South_(Gaskell_novel)

**Comment by dajare** [comment]
@b-t-k  Wow! :grin: So close to *producing* my first "perfect" book!! Don't know how I messed that URL, in particular. :man_shrugging: 

All dealt with in b455629 — I tightened up that sentence in the long desc; hope it's an improvement.

If you're content with these tweaks, I guess it's over to Alex. :)
